# Generated by Django 4.0.3 on 2022-03-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='org',
        ),
        migrations.AddField(
            model_name='certificatedetails',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
