# Generated by Django 4.0.3 on 2022-03-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_remove_participant_org_certificatedetails_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatedetails',
            name='org_column',
        ),
    ]
